package cn.ac.bcc.maque.model;
// Generated 2016-5-11 17:35:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user",schema="myschema")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5656136547913487597L;
	
	@Id
	@Column(name="id")
	private String id;
	@Column(name="name")
	private String name;
	@Column(name="signup_date")
	private Date signupDate;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getSignupDate() {
		return this.signupDate;
	}

	public void setSignupDate(Date signupDate) {
		this.signupDate = signupDate;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof User))
			return false;
		User castOther = (User) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getSignupDate() == castOther.getSignupDate())
						|| (this.getSignupDate() != null && castOther.getSignupDate() != null
								&& this.getSignupDate().equals(castOther.getSignupDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getSignupDate() == null ? 0 : this.getSignupDate().hashCode());
		return result;
	}

}
